# Generated by Django 5.0.3 on 2024-03-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.FloatField()),
            ],
            options={
                'db_table': 'venta',
                'managed': True,
            },
        ),
    ]
