# Generated by Django 5.0.3 on 2024-03-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_app', '0002_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='productos/generico.jpg', upload_to='productos/'),
        ),
    ]
