# Generated by Django 5.0.3 on 2024-03-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_app', '0003_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='productos/generico.jpg', upload_to='productos'),
        ),
    ]
